services:
#  redis:
#    image: redis:7-alpine
#    container_name: airo-redis-server
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    restart: unless-stopped
#    command: redis-server --appendonly yes
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AIRO
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_ACCESS: ${JWT_EXPIRATION_ACCESS}
      JWT_EXPIRATION_REFRESH: ${JWT_EXPIRATION_REFRESH}

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
volumes:
  redis_data:
